Make git apply context configurable
jeffpc/guilt pull request #2
Opened 2016-10-04 15:53 UTC by srowe

Experience has shown that limiting context to a single line can result
in patches silently applying at the wrong location. Add a config
parameter guilt.diffcontext that is either 'true' (use all context) or
the number of lines to match.

The default for guilt.diffcontext remains as one line.

Signed-off-by: Simon Rowe <simon.rowe@eu.citrix.com>

2016-10-04 16:21 UTC, jeffpc requested changes

2016-10-04 16:21 UTC, jeffpc commented on guilt
> +[ "$diffcontext" != "true" ] && guilt_push_diff_context="-C$diffcontext"
(Ok, let's see how these new github review comments work...)

I haven't tried it, but wouldn't a `false` setting result in calling `git apply -Cfalse`?

Overall, this seems like a reasonable approach for an immediate fix.  Ultimately, it'd be nice to see this code get more attention.  I bet there is a better way of applying patches than just mucking with context to git-apply.  (E.g., it'd be nice to make use of the available history to perform something like a 3-way merge.)

2016-10-05 08:30 UTC, srowe commented on guilt
> +[ "$diffcontext" != "true" ] && guilt_push_diff_context="-C$diffcontext"
I've changed this to map as follows:

- `true` (nothing)
- `false` becomes  `-C0`
- `int` becomes `-Cint`

In the long-term could patches not be applied using `git am`?

2016-10-10 11:42 UTC, srowe commented on guilt
> +[ "$diffcontext" != "true" ] && guilt_push_diff_context="-C$diffcontext"
Any thoughts on the updated changeset?

2016-10-10 14:06 UTC, jeffpc commented
I changed it up a little bit and pushed it to my `tmp` branch - if you could give that a try and let me know if that works for you, I'll push it to master.

2016-10-11 07:57 UTC, srowe commented
Thanks, this works fine for me.

2016-10-11 16:24 UTC, closed without merging